In [2]:
import tensorflow as tf
import numpy as np

In [3]:
class NN():
    def __init__(self):
        self.A     = tf.Variable(np.random.rand(3), dtype=tf.float32, name='A')
        self.A_PH  = tf.placeholder(dtype=tf.float32, shape=(3,), name='A_PH')
        self.A_ass = tf.assign(self.A, self.A_PH, name='A_ass')
        self.init  = tf.global_variables_initializer()
        
    def getWeights(self, sess=None):
        if sess is not None:
            return sess.run(self.A)
        with tf.Session() as sess:
            sess.run(self.init)
            return sess.run(self.A)
        
    def setWeights(self, val, sess):
        sess.run(self.A_ass, feed_dict={'A_PH:0':val})

In [10]:
x = NN()
val = x.getWeights()
val1 = val + 5
with tf.Session() as sess:
    sess.run(x.init)
    x.setWeights(val1, sess)
    val2 = x.getWeights(sess)
print(val)
print(val1)
print(val2)

InvalidArgumentError: You must feed a value for placeholder tensor 'A_PH_2' with dtype float and shape [3]
	 [[Node: A_PH_2 = Placeholder[dtype=DT_FLOAT, shape=[3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'A_PH_2', defined at:
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-c19527d9a1d9>", line 1, in <module>
    x = NN()
  File "<ipython-input-3-1be308e2383c>", line 4, in __init__
    self.A_PH  = tf.placeholder(dtype=tf.float32, shape=(3,), name='A_PH')
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1599, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3091, in _placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'A_PH_2' with dtype float and shape [3]
	 [[Node: A_PH_2 = Placeholder[dtype=DT_FLOAT, shape=[3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [5]:
class AA():
    def __init__(self, N):
        self.tempN = N()

In [6]:
y = AA(NN)

In [7]:
val = y.tempN.getWeights()
val1 = val + 5
with tf.Session() as sess:
    sess.run(y.tempN.init)
    y.tempN.setWeights(val1, sess)
    val2 = y.tempN.getWeights(sess)
print(val)
print(val1)
print(val2)

[ 0.54041982  0.65165329  0.41137883]
[ 5.54041958  5.65165329  5.41137886]
[ 5.54041958  5.65165329  5.41137886]
